type Meter implements BaseObject {
  meterNumber: String!
  location: String
  ID: ID!
  updatedBy: User
  createdBy: User
}

input NewMeter {
  meterNumber: String!
  location: String
}

extend type Query {
  meters(limit: Int = 10, after: ID = null): [Meter]!
}

extend type Mutation {
  createMeter(input: NewMeter!): Meter!
}

extend type Subscription {
  createMeter(input: NewMeter!): Meter!
}
