type Meter implements BaseObject {
  meterNumber: String!
  ID: ID!
  updatedBy: User
  createdBy: User
  active: Boolean!
}

input NewMeter {
  meterNumber: String!
  location: String
}

extend type Query {
  meters(limit: Int = 10, after: ID = null): MeterConnection!
}

extend type Mutation {
  createMeter(input: NewMeter!): Meter!
  disableMeter(meterNumber: String!): Meter!
  enableMeter(meterNumber: String!): Meter!
  # updateMeter(input: NewMeter!): Meter!
}

type MeterConnection {
  "A list of the meters, paginated by the provided values"
  data: [Meter!]
  "Information for paginating this connection"
  pageInfo: PageInfo!
}
