type Token implements BaseObject {
  meterNumber: String!
  tokenString: String!
  ID: ID!
  updatedBy: User
  createdBy: User
}

extend type Query {
  tokens(limit: Int = 10, after: ID = null): TokenConnection!
}

extend type Subscription {
  tokenCreated(meterNumber: String): Token!
}

type TokenConnection {
  "A list of the meters, paginated by the provided values"
  data: [Token!]
  "Information for paginating this connection"
  pageInfo: PageInfo!
}
