type Token {
  meterNumber: String!
  tokenString: String!
  ID: ID!
  status: Int!
  apiKey: ID!
}

extend type Query {
  getTokens(
    limit: Int = 30
    after: ID = null
    meterNumber: String
  ): TokenConnection!
}

extend type Subscription {
  tokenCreated(meterNumber: String): Token!
}

type TokenConnection {
  "A list of the meters, paginated by the provided values"
  data: [Token!]
  "Information for paginating this connection"
  pageInfo: PageInfo!
}
