type User {
  ID: ID!
  email: String!
}

input NewUser {
  email: String!
}

extend type Query {
  users(limit: Int = 10, after: ID = null): [User]!
}

extend type Mutation {
  createUser(input: NewMeter!): User!
}
