type User implements BaseObject {
  email: String!
  ID: ID!
  name: String!
  updatedBy: User
  createdBy: User
}

input NewUser {
  name: String!
  email: String!
}

extend type Query {
  users(limit: Int = 10, after: ID = null): UsersConnection!
}

type UsersConnection {
  "A list of the meters, paginated by the provided values"
  data: [User!]
  "Information for paginating this connection"
  pageInfo: PageInfo!
}

extend type Mutation {
  createUser(input: NewUser!): User!
  disableUser(email: String!): User!
  updateUser(input: NewUser!): User!
}
