type User implements BaseObject {
  email: String!
  ID: ID!
  updatedBy: User
  createdBy: User
}

input NewUser {
  name: String!
  email: String!
}

extend type Query {
  users(limit: Int = 10, after: ID = null): [User]!
}

extend type Mutation {
  createUser(input: NewUser!): User!
  disableUser(email: String!): User!
  updateUser(input: NewUser!): User!
}
